### ISSUE TITLE
IPad support

### ISSUE THREAD

**Issue by mayshaw** [GMOD/jbrowse#439]
Is the newest version of JBrowse supporting IPad touch? Thank you.

**Comment by lukaw3d** [comment]
Was iPad support later dropped?
http://jbrowse.org/releases/JBrowse-1.11.6.zip does not seem to support it:
* it is missing touch files `TouchScroll.js`, `util/has-css3.js`, `util/touch.js`
* it is throwing errors after I manually added the files

**Comment by cmdcolin** [comment]
I don't have a real ipad for testing but it works on an ios simulator

<img width="1440" alt="ipad" src="https://cloud.githubusercontent.com/assets/6511937/10284857/be254c3c-6b4b-11e5-851c-316524b113ea.png">


I have also heard it works on a real ipad too :smiley: 




I think those problems with touchscroll files being missing were fixed in version 1.11.5 according to release notes.

Can you load the jbrowse homepage on your ipad for test?

**Comment by lukaw3d** [comment]
Oh, my mistake, in some parts of the app I still had 1.11.4 instead of 1.11.6.

After I updated all to 1.11.6 I didnt have any issues with touch files, however I am still getting "Illegal invocation" errors when I drag left/right in iPad simulator. And on the real iPad dragging left/right doesn't work either, but otherwise it works!

**Comment by cmdcolin** [comment]
ah that is too bad. I think i can confirm the side scroll has some issues in the simulator. It would be nice if the side swipe to scroll worked.

I think side swipe to scroll worked on another android based tablet so thats kind of odd

**Comment by cmdcolin** [comment]
Maybe related


https://bugs.dojotoolkit.org/ticket/18168


I think jbrowse is currently at 1.9.1 of dojo, but it says something related to this was fixed in 1.9.4

**Comment by cmdcolin** [comment]
Yep...upgrading versions to better dojo fixes it. also...I think we should move to this system to make it easier to manage dependencies https://github.com/GMOD/jbrowse/pull/333

**Comment by lukaw3d** [comment]
Great, thanks for checking that out
